### ISSUE TITLE
I ported `base65536` to the UNIX shell

### ISSUE THREAD

**Issue by girst** [ferno/base65536#3]
I know this isn't really an issue, but there isn't private messaging on GitHub. 

As the title says - you can now en- and decode your precious strings and blobs in the same way as one would use the `base64` tool included in most Linux distributions. 

The project lives at: https://github.com/girst/base65536

I would be honored if you were to mention my projekt in your README.md. 

Thanks, 
Tobias

**Comment by ferno** [comment]
Duly noted, thanks for the update!
